# Copyright Broadcom, Inc. All Rights Reserved.
# SPDX-License-Identifier: APACHE-2.0

name: mdlqa-pgsql
services:
#   postgresql:
#     image: docker.io/bitnami/postgresql:17
#     environment:
#       # ALLOW_EMPTY_PASSWORD is recommended only for development.
#       #- ALLOW_EMPTY_PASSWORD=yes
#       - POSTGRESQL_USERNAME=bn_moodle
#       - POSTGRESQL_PASSWORD=${POSTGRESQL_PASSWORD}
#       - POSTGRESQL_DATABASE=bitnami_moodle
# #      - POSTGRESQL_CHARACTER_SET=utf8mb4
# #      - POSTGRESQL_COLLATE=utf8mb4_unicode_ci
#     volumes:
#       - 'db_data:/bitnami/postgresql'
#     networks:
#       - mdl_pgsql_net
  postgresql:
    image: postgres:alpine
    environment:
      # ALLOW_EMPTY_PASSWORD is recommended only for development.
      #- ALLOW_EMPTY_PASSWORD=yes
      - POSTGRES_DB=bitnami_moodle
      - POSTGRES_USER=bn_moodle
      - POSTGRES_PASSWORD=${POSTGRESQL_PASSWORD}
#      - POSTGRESQL_CHARACTER_SET=utf8mb4
#      - POSTGRESQL_COLLATE=utf8mb4_unicode_ci
    volumes:
      - db_data:/var/lib/postgresql/data
    networks:
      - mdl_pgsql_net
  moodle:
    #image: docker.io/bitnami/moodle:4.4
    build:
        context: .
        dockerfile: Dockerfile
    ports:
      - '80:8080'
      - '443:8443'
    environment:
      - MOODLE_DATABASE_HOST=postgresql
      - MOODLE_DATABASE_TYPE=pgsql
      - MOODLE_DATABASE_PORT_NUMBER=5432
      - MOODLE_DATABASE_USER=bn_moodle
      - MOODLE_DATABASE_NAME=bitnami_moodle
      - MOODLE_DATABASE_PASSWORD=${POSTGRESQL_PASSWORD}
      - MOODLE_USERNAME=admin
      - MOODLE_PASSWORD=${MOODLE_PASSWORD}
      # ALLOW_EMPTY_PASSWORD is recommended only for development.
      #- ALLOW_EMPTY_PASSWORD=yes
      - MOODLE_SMTP_HOST=mailpit
      - MOODLE_SMTP_PORT=1025
      - MOODLE_SMTP_USER=admin
      - MOODLE_SMTP_PASSWORD=${MOODLE_PASSWORD}
      - MOODLE_SMTP_PROTOCOL=
    volumes:
      - 'moodle_data:/bitnami/moodle'
      - 'moodledata_data:/bitnami/moodledata'
    depends_on:
      - postgresql
      - mailpit
    networks:
      - mdl_pgsql_net

      # https://mailpit.axllent.org/
  mailpit: # You need to ensure you map the correct ports (default Web UI on 8025 and SMTP on 1025).
    image: axllent/mailpit:latest
    volumes:
      - 'mailpit_data:/data'
    ports:
      - 8025:8025
      - 1025:1025
    environment:
      MP_MAX_MESSAGES: 5000
      MP_DATA_FILE: /data/mailpit.db
      MP_SMTP_AUTH_ACCEPT_ANY: 1
      MP_SMTP_AUTH_ALLOW_INSECURE: 1 
    networks:
      - mdl_pgsql_net
volumes:
  db_data:
    driver: local
  moodle_data:
    driver: local
  moodledata_data:
    driver: local
  mailpit_data:
    driver: local
networks:
  mdl_pgsql_net:
    driver: bridge
